//
//  Pokemon+Evolving.swift
//  pokemons
//
//  Created by James Taylor on 2016-08-03.
//  Copyright © 2016 James Taylor. All rights reserved.
//

import Foundation

extension Pokemon: Evolving {
    var evolved: Pokemon? {
        switch self {
        case .bulbasaur: return .ivysaur
        case .ivysaur: return .venusaur
        case .venusaur: return nil
        case .charmander: return .charmeleon
        case .charmeleon: return .charizard
        case .charizard: return nil
        case .squirtle: return .wartortle
        case .wartortle: return .blastoise
        case .blastoise: return nil
        case .caterpie: return .metapod
        case .metapod: return .butterfree
        case .butterfree: return nil
        case .weedle: return .kakuna
        case .kakuna: return .beedrill
        case .beedrill: return nil
        case .pidgey: return .pidgeotto
        case .pidgeotto: return .pidgeot
        case .pidgeot: return nil
        case .rattata: return .raticate
        case .raticate: return nil
        case .spearow: return .fearow
        case .fearow: return nil
        case .ekans: return .arbok
        case .arbok: return nil
        case .pikachu: return .raichu
        case .raichu: return nil
        case .sandshrew: return .sandslash
        case .sandslash: return nil
        case .nidoranf: return .nidorina
        case .nidorina: return .nidoqueen
        case .nidoqueen: return nil
        case .nidoranm: return .nidorino
        case .nidorino: return .nidoking
        case .nidoking: return nil
        case .clefairy: return .clefable
        case .clefable: return nil
        case .vulpix: return .ninetales
        case .ninetales: return nil
        case .jigglypuff: return .wigglytuff
        case .wigglytuff: return nil
        case .zubat: return .golbat
        case .golbat: return nil
        case .oddish: return .gloom
        case .gloom: return .vileplume
        case .vileplume: return nil
        case .paras: return .parasect
        case .parasect: return nil
        case .venonat: return .venomoth
        case .venomoth: return nil
        case .diglett: return .dugtrio
        case .dugtrio: return nil
        case .meowth: return .persian
        case .persian: return nil
        case .psyduck: return .golduck
        case .golduck: return nil
        case .mankey: return .primeape
        case .primeape: return nil
        case .growlithe: return .arcanine
        case .arcanine: return nil
        case .poliwag: return .poliwhirl
        case .poliwhirl: return .poliwrath
        case .poliwrath: return nil
        case .abra: return .kadabra
        case .kadabra: return .alakazam
        case .alakazam: return nil
        case .machop: return .machoke
        case .machoke: return .machamp
        case .machamp: return nil
        case .bellsprout: return .weepinbell
        case .weepinbell: return .victreebel
        case .victreebel: return nil
        case .tentacool: return .tentacruel
        case .tentacruel: return nil
        case .geodude: return .graveler
        case .graveler: return .golem
        case .golem: return nil
        case .ponyta: return .rapidash
        case .rapidash: return nil
        case .slowpoke: return .slowbro
        case .slowbro: return nil
        case .magnemite: return .magneton
        case .magneton: return nil
        case .farfetchd: return nil
        case .doduo: return .dodrio
        case .dodrio: return nil
        case .seel: return .dewgong
        case .dewgong: return nil
        case .grimer: return .muk
        case .muk: return nil
        case .shellder: return .cloyster
        case .cloyster: return nil
        case .gastly: return .haunter
        case .haunter: return .gengar
        case .gengar: return nil
        case .onix: return nil
        case .drowzee: return .hypno
        case .hypno: return nil
        case .krabby: return .kingler
        case .kingler: return nil
        case .voltorb: return .electrode
        case .electrode: return nil
        case .exeggcute: return .exeggutor
        case .exeggutor: return nil
        case .cubone: return .marowak
        case .marowak: return nil
        case .hitmonlee: return nil
        case .hitmonchan: return nil
        case .lickitung: return nil
        case .koffing: return .weezing
        case .weezing: return nil
        case .rhyhorn: return .rhydon
        case .rhydon: return nil
        case .chansey: return nil
        case .tangela: return nil
        case .kangaskhan: return nil
        case .horsea: return .seadra
        case .seadra: return nil
        case .goldeen: return .seaking
        case .seaking: return nil
        case .staryu: return .starmie
        case .starmie: return nil
        case .mrmime: return nil
        case .scyther: return nil
        case .jynx: return nil
        case .electabuzz: return nil
        case .magmar: return nil
        case .pinsir: return nil
        case .tauros: return nil
        case .magikarp: return .gyarados
        case .gyarados: return nil
        case .lapras: return nil
        case .ditto: return nil
        case .eevee: return .vaporeon
        case .vaporeon: return .jolteon
        case .jolteon: return .flareon
        case .flareon: return nil
        case .porygon: return nil
        case .omanyte: return .omastar
        case .omastar: return nil
        case .kabuto: return .kabutops
        case .kabutops: return nil
        case .aerodactyl: return nil
        case .snorlax: return nil
        case .articuno: return nil
        case .zapdos: return nil
        case .moltres: return nil
        case .dratini: return .dragonair
        case .dragonair: return .dragonite
        case .dragonite: return nil
        case .mewtwo: return nil
        case .mew: return nil
        }
    }
    
    var unevolved: Pokemon? {
        switch self {
        case .bulbasaur: return nil
        case .ivysaur: return .bulbasaur
        case .venusaur: return .ivysaur
        case .charmander: return nil
        case .charmeleon: return .charmander
        case .charizard: return .charmeleon
        case .squirtle: return nil
        case .wartortle: return .squirtle
        case .blastoise: return .wartortle
        case .caterpie: return nil
        case .metapod: return .caterpie
        case .butterfree: return .metapod
        case .weedle: return nil
        case .kakuna: return .weedle
        case .beedrill: return .kakuna
        case .pidgey: return nil
        case .pidgeotto: return .pidgey
        case .pidgeot: return .pidgeotto
        case .rattata: return nil
        case .raticate: return .rattata
        case .spearow: return nil
        case .fearow: return .spearow
        case .ekans: return nil
        case .arbok: return .ekans
        case .pikachu: return nil
        case .raichu: return .pikachu
        case .sandshrew: return nil
        case .sandslash: return .sandshrew
        case .nidoranf: return nil
        case .nidorina: return .nidoranf
        case .nidoqueen: return .nidorina
        case .nidoranm: return nil
        case .nidorino: return .nidoranm
        case .nidoking: return .nidorino
        case .clefairy: return nil
        case .clefable: return .clefairy
        case .vulpix: return nil
        case .ninetales: return .vulpix
        case .jigglypuff: return nil
        case .wigglytuff: return .jigglypuff
        case .zubat: return nil
        case .golbat: return .zubat
        case .oddish: return nil
        case .gloom: return .oddish
        case .vileplume: return .gloom
        case .paras: return nil
        case .parasect: return .paras
        case .venonat: return nil
        case .venomoth: return .venonat
        case .diglett: return nil
        case .dugtrio: return .diglett
        case .meowth: return nil
        case .persian: return .meowth
        case .psyduck: return nil
        case .golduck: return .psyduck
        case .mankey: return nil
        case .primeape: return .mankey
        case .growlithe: return nil
        case .arcanine: return .growlithe
        case .poliwag: return nil
        case .poliwhirl: return .poliwag
        case .poliwrath: return .poliwhirl
        case .abra: return nil
        case .kadabra: return .abra
        case .alakazam: return .kadabra
        case .machop: return nil
        case .machoke: return .machop
        case .machamp: return .machoke
        case .bellsprout: return nil
        case .weepinbell: return .bellsprout
        case .victreebel: return .weepinbell
        case .tentacool: return nil
        case .tentacruel: return .tentacool
        case .geodude: return nil
        case .graveler: return .geodude
        case .golem: return .graveler
        case .ponyta: return nil
        case .rapidash: return .ponyta
        case .slowpoke: return nil
        case .slowbro: return .slowpoke
        case .magnemite: return nil
        case .magneton: return .magnemite
        case .farfetchd: return nil
        case .doduo: return nil
        case .dodrio: return .doduo
        case .seel: return nil
        case .dewgong: return .seel
        case .grimer: return nil
        case .muk: return .grimer
        case .shellder: return nil
        case .cloyster: return .shellder
        case .gastly: return nil
        case .haunter: return .gastly
        case .gengar: return .haunter
        case .onix: return nil
        case .drowzee: return nil
        case .hypno: return .drowzee
        case .krabby: return nil
        case .kingler: return .krabby
        case .voltorb: return nil
        case .electrode: return .voltorb
        case .exeggcute: return nil
        case .exeggutor: return .exeggcute
        case .cubone: return nil
        case .marowak: return .cubone
        case .hitmonlee: return nil
        case .hitmonchan: return nil
        case .lickitung: return nil
        case .koffing: return nil
        case .weezing: return .koffing
        case .rhyhorn: return nil
        case .rhydon: return .rhyhorn
        case .chansey: return nil
        case .tangela: return nil
        case .kangaskhan: return nil
        case .horsea: return nil
        case .seadra: return .horsea
        case .goldeen: return nil
        case .seaking: return .goldeen
        case .staryu: return nil
        case .starmie: return .staryu
        case .mrmime: return nil
        case .scyther: return nil
        case .jynx: return nil
        case .electabuzz: return nil
        case .magmar: return nil
        case .pinsir: return nil
        case .tauros: return nil
        case .magikarp: return nil
        case .gyarados: return .magikarp
        case .lapras: return nil
        case .ditto: return nil
        case .eevee: return nil
        case .vaporeon: return .eevee
        case .jolteon: return .vaporeon
        case .flareon: return .jolteon
        case .porygon: return nil
        case .omanyte: return nil
        case .omastar: return .omanyte
        case .kabuto: return nil
        case .kabutops: return .kabuto
        case .aerodactyl: return nil
        case .snorlax: return nil
        case .articuno: return nil
        case .zapdos: return nil
        case .moltres: return nil
        case .dratini: return nil
        case .dragonair: return .dratini
        case .dragonite: return .dragonair
        case .mewtwo: return nil
        case .mew: return nil
        }
    }
}
