//
//  Pokemon.swift
//  pokemons
//
//  Created by James Taylor on 2016-08-03.
//  Copyright © 2016 James Taylor. All rights reserved.
//

import Foundation

public enum Pokemon: Int {
    case bulbasaur = 1, ivysaur, venusaur, charmander, charmeleon, charizard, squirtle, wartortle, blastoise, caterpie, metapod, butterfree, weedle, kakuna, beedrill, pidgey, pidgeotto, pidgeot, rattata, raticate, spearow, fearow, ekans, arbok, pikachu, raichu, sandshrew, sandslash, nidoranf, nidorina, nidoqueen, nidoranm, nidorino, nidoking, clefairy, clefable, vulpix, ninetales, jigglypuff, wigglytuff, zubat, golbat, oddish, gloom, vileplume, paras, parasect, venonat, venomoth, diglett, dugtrio, meowth, persian, psyduck, golduck, mankey, primeape, growlithe, arcanine, poliwag, poliwhirl, poliwrath, abra, kadabra, alakazam, machop, machoke, machamp, bellsprout, weepinbell, victreebel, tentacool, tentacruel, geodude, graveler, golem, ponyta, rapidash, slowpoke, slowbro, magnemite, magneton, farfetchd, doduo, dodrio, seel, dewgong, grimer, muk, shellder, cloyster, gastly, haunter, gengar, onix, drowzee, hypno, krabby, kingler, voltorb, electrode, exeggcute, exeggutor, cubone, marowak, hitmonlee, hitmonchan, lickitung, koffing, weezing, rhyhorn, rhydon, chansey, tangela, kangaskhan, horsea, seadra, goldeen, seaking, staryu, starmie, mrmime, scyther, jynx, electabuzz, magmar, pinsir, tauros, magikarp, gyarados, lapras, ditto, eevee, vaporeon, jolteon, flareon, porygon, omanyte, omastar, kabuto, kabutops, aerodactyl, snorlax, articuno, zapdos, moltres, dratini, dragonair, dragonite, mewtwo, mew
    
    static let all: [Pokemon] = [.bulbasaur, .ivysaur, .venusaur, .charmander, .charmeleon, .charizard, .squirtle, .wartortle, .blastoise, .caterpie, .metapod, .butterfree, .weedle, .kakuna, .beedrill, .pidgey, .pidgeotto, .pidgeot, .rattata, .raticate, .spearow, .fearow, .ekans, .arbok, .pikachu, .raichu, .sandshrew, .sandslash, .nidoranf, .nidorina, .nidoqueen, .nidoranm, .nidorino, .nidoking, .clefairy, .clefable, .vulpix, .ninetales, .jigglypuff, .wigglytuff, .zubat, .golbat, .oddish, .gloom, .vileplume, .paras, .parasect, .venonat, .venomoth, .diglett, .dugtrio, .meowth, .persian, .psyduck, .golduck, .mankey, .primeape, .growlithe, .arcanine, .poliwag, .poliwhirl, .poliwrath, .abra, .kadabra, .alakazam, .machop, .machoke, .machamp, .bellsprout, .weepinbell, .victreebel, .tentacool, .tentacruel, .geodude, .graveler, .golem, .ponyta, .rapidash, .slowpoke, .slowbro, .magnemite, .magneton, .farfetchd, .doduo, .dodrio, .seel, .dewgong, .grimer, .muk, .shellder, .cloyster, .gastly, .haunter, .gengar, .onix, .drowzee, .hypno, .krabby, .kingler, .voltorb, .electrode, .exeggcute, .exeggutor, .cubone, .marowak, .hitmonlee, .hitmonchan, .lickitung, .koffing, .weezing, .rhyhorn, .rhydon, .chansey, .tangela, .kangaskhan, .horsea, .seadra, .goldeen, .seaking, .staryu, .starmie, .mrmime, .scyther, .jynx, .electabuzz, .magmar, .pinsir, .tauros, .magikarp, .gyarados, .lapras, .ditto, .eevee, .vaporeon, .jolteon, .flareon, .porygon, .omanyte, .omastar, .kabuto, .kabutops, .aerodactyl, .snorlax, .articuno, .zapdos, .moltres, .dratini, .dragonair, .dragonite, .mewtwo, .mew]
}

public extension Pokemon {
    
    /// identical to `init(rawValue:)`.
    init?(id: Int) { self.init(rawValue: id) }
    
    /// identical to `rawValue`
    var id: Int { return self.rawValue }
    
    var name: String {
        switch self {
        case .bulbasaur: return "bulbasaur"
        case .ivysaur: return "ivysaur"
        case .venusaur: return "venusaur"
        case .charmander: return "charmander"
        case .charmeleon: return "charmeleon"
        case .charizard: return "charizard"
        case .squirtle: return "squirtle"
        case .wartortle: return "wartortle"
        case .blastoise: return "blastoise"
        case .caterpie: return "caterpie"
        case .metapod: return "metapod"
        case .butterfree: return "butterfree"
        case .weedle: return "weedle"
        case .kakuna: return "kakuna"
        case .beedrill: return "beedrill"
        case .pidgey: return "pidgey"
        case .pidgeotto: return "pidgeotto"
        case .pidgeot: return "pidgeot"
        case .rattata: return "rattata"
        case .raticate: return "raticate"
        case .spearow: return "spearow"
        case .fearow: return "fearow"
        case .ekans: return "ekans"
        case .arbok: return "arbok"
        case .pikachu: return "pikachu"
        case .raichu: return "raichu"
        case .sandshrew: return "sandshrew"
        case .sandslash: return "sandslash"
        case .nidoranf: return "nidoran♀"
        case .nidorina: return "nidorina"
        case .nidoqueen: return "nidoqueen"
        case .nidoranm: return "nidoran♂"
        case .nidorino: return "nidorino"
        case .nidoking: return "nidoking"
        case .clefairy: return "clefairy"
        case .clefable: return "clefable"
        case .vulpix: return "vulpix"
        case .ninetales: return "ninetales"
        case .jigglypuff: return "jigglypuff"
        case .wigglytuff: return "wigglytuff"
        case .zubat: return "zubat"
        case .golbat: return "golbat"
        case .oddish: return "oddish"
        case .gloom: return "gloom"
        case .vileplume: return "vileplume"
        case .paras: return "paras"
        case .parasect: return "parasect"
        case .venonat: return "venonat"
        case .venomoth: return "venomoth"
        case .diglett: return "diglett"
        case .dugtrio: return "dugtrio"
        case .meowth: return "meowth"
        case .persian: return "persian"
        case .psyduck: return "psyduck"
        case .golduck: return "golduck"
        case .mankey: return "mankey"
        case .primeape: return "primeape"
        case .growlithe: return "growlithe"
        case .arcanine: return "arcanine"
        case .poliwag: return "poliwag"
        case .poliwhirl: return "poliwhirl"
        case .poliwrath: return "poliwrath"
        case .abra: return "abra"
        case .kadabra: return "kadabra"
        case .alakazam: return "alakazam"
        case .machop: return "machop"
        case .machoke: return "machoke"
        case .machamp: return "machamp"
        case .bellsprout: return "bellsprout"
        case .weepinbell: return "weepinbell"
        case .victreebel: return "victreebel"
        case .tentacool: return "tentacool"
        case .tentacruel: return "tentacruel"
        case .geodude: return "geodude"
        case .graveler: return "graveler"
        case .golem: return "golem"
        case .ponyta: return "ponyta"
        case .rapidash: return "rapidash"
        case .slowpoke: return "slowpoke"
        case .slowbro: return "slowbro"
        case .magnemite: return "magnemite"
        case .magneton: return "magneton"
        case .farfetchd: return "farfetchd"
        case .doduo: return "doduo"
        case .dodrio: return "dodrio"
        case .seel: return "seel"
        case .dewgong: return "dewgong"
        case .grimer: return "grimer"
        case .muk: return "muk"
        case .shellder: return "shellder"
        case .cloyster: return "cloyster"
        case .gastly: return "gastly"
        case .haunter: return "haunter"
        case .gengar: return "gengar"
        case .onix: return "onix"
        case .drowzee: return "drowzee"
        case .hypno: return "hypno"
        case .krabby: return "krabby"
        case .kingler: return "kingler"
        case .voltorb: return "voltorb"
        case .electrode: return "electrode"
        case .exeggcute: return "exeggcute"
        case .exeggutor: return "exeggutor"
        case .cubone: return "cubone"
        case .marowak: return "marowak"
        case .hitmonlee: return "hitmonlee"
        case .hitmonchan: return "hitmonchan"
        case .lickitung: return "lickitung"
        case .koffing: return "koffing"
        case .weezing: return "weezing"
        case .rhyhorn: return "rhyhorn"
        case .rhydon: return "rhydon"
        case .chansey: return "chansey"
        case .tangela: return "tangela"
        case .kangaskhan: return "kangaskhan"
        case .horsea: return "horsea"
        case .seadra: return "seadra"
        case .goldeen: return "goldeen"
        case .seaking: return "seaking"
        case .staryu: return "staryu"
        case .starmie: return "starmie"
        case .mrmime: return "mr. mime"
        case .scyther: return "scyther"
        case .jynx: return "jynx"
        case .electabuzz: return "electabuzz"
        case .magmar: return "magmar"
        case .pinsir: return "pinsir"
        case .tauros: return "tauros"
        case .magikarp: return "magikarp"
        case .gyarados: return "gyarados"
        case .lapras: return "lapras"
        case .ditto: return "ditto"
        case .eevee: return "eevee"
        case .vaporeon: return "vaporeon"
        case .jolteon: return "jolteon"
        case .flareon: return "flareon"
        case .porygon: return "porygon"
        case .omanyte: return "omanyte"
        case .omastar: return "omastar"
        case .kabuto: return "kabuto"
        case .kabutops: return "kabutops"
        case .aerodactyl: return "aerodactyl"
        case .snorlax: return "snorlax"
        case .articuno: return "articuno"
        case .zapdos: return "zapdos"
        case .moltres: return "moltres"
        case .dratini: return "dratini"
        case .dragonair: return "dragonair"
        case .dragonite: return "dragonite"
        case .mewtwo: return "mewtwo"
        case .mew: return "mew"
        }
    }
}



